spring:
  profiles:
    active:
    - "@web-profile@"
    - "@security-profile@"
    - "@service-profile@"
    - "@persistence-profile@"
    - "@common-profile@"

my-variables:
  version:
    profile: "@profileName@"
    serial: 1