spring:
  datasource:
    url: jdbc:mysql:///todolistdb-local?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: todolist
    password: todolist
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

my-variables:
  persistence:
    env: local-persistence